# Generated by Django 5.2.8 on 2025-11-29 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_venta_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Creacion', 'Creacion'), ('Eliminacion', 'Eliminacion')], max_length=20),
        ),
    ]
